### ISSUE TITLE
Shadow with AspectJ aspects error

### ISSUE THREAD

**Issue by sergeykad** [GradleUp/shadow#234]
### Actual Behavior Aspects fail to load

Tried several Java versions from 6 to 8.
AspectJ 1.8.9

Shadow modifies aspect class files regardless if it is actually required or not. If change was not required it is possible to work around the problem by copying overwriting aspects class files in the fat (shadow) with ones from original (slim) jar.

As I understand it, BCEL cannot read class atributes. 

The following exceptions are thrown during startup:

<pre>
SEVERE: register definition failed
java.lang.RuntimeException: Problem processing attributes in com.my.GreatAspect
        at org.aspectj.weaver.bcel.BcelObjectType.ensureAspectJAttributesUnpacked(BcelObjectType.java:387)
        at org.aspectj.weaver.bcel.BcelObjectType.<init>(BcelObjectType.java:162)
        at org.aspectj.weaver.bcel.BcelWorld.buildBcelDelegate(BcelWorld.java:410)
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:405)
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107)
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:478)
        at org.aspectj.weaver.World.resolve(World.java:319)
        at org.aspectj.weaver.bcel.BcelWeaver.addLibraryAspect(BcelWeaver.java:159)
        at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.registerAspects(ClassLoaderWeavingAdaptor.java:485)
        at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.registerDefinitions(ClassLoaderWeavingAdaptor.java:304)
        at org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor.initialize(ClassLoaderWeavingAdaptor.java:171)
        at org.aspectj.weaver.loadtime.Aj$ExplicitlyInitializedClassLoaderWeavingAdaptor.initialize(Aj.java:340)
        at org.aspectj.weaver.loadtime.Aj$ExplicitlyInitializedClassLoaderWeavingAdaptor.getWeavingAdaptor(Aj.java:345)
        at org.aspectj.weaver.loadtime.Aj$WeaverContainer.getWeaver(Aj.java:319)
        at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:113)
        at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:54)
<pre>

**Comment by johnrengelman** [comment]
can you post an example project. I'm not very educated in AspectJ, so I'll need help in this area.

**Comment by sergeykad** [comment]
I'll try to prepare/find something suitable for the problem demonstration.

The main problem IMHO is that Shadow performs many manipulations to classes that seems to be excessive. I noticed many changes in the class that remained in its original package and do not use any classes that were moved to another package. Such class could be copied to the fat jar as is, but multiple modifications were performed on it.

**Comment by sergeykad** [comment]
A project that demonstrates the problem is attached. 
I got error uploading ZIP file, so I changed the extension to PDF.
[aspect-demo.zip.pdf](https://github.com/johnrengelman/shadow/files/412894/aspect-demo.zip.pdf)

**Comment by johnrengelman** [comment]
the easiest thing to do is post this code in a public GitHub repo

**Comment by sergeykad** [comment]
Here you go https://github.com/sergeykad/AspectJ-Shadow

**Comment by Goooler** [comment]
@sergeykad Can you try with the latest version?

**Comment by Goooler** [comment]
I'll close this until someone complains again.
