### ISSUE TITLE
Doesn't generate META-INF with Gradle 5.0

### ISSUE THREAD

**Issue by hiteshsharma** [GradleUp/shadow#464]
Gradle Task:
```
shadowJar {
  archiveName = 'benchmarks.jar'
  classifier = 'benchmarks'
  manifest {
    attributes 'Main-Class': 'org.openjdk.jmh.Main'
  }
  outputs.upToDateWhen { false }
}
```
shadow Plugin version: `4.0.3`

Task runs successfully but on running benchmarks I get this
```
/export/apps/jdk/JDK-1_8_0_121/bin/java -Dfile.encoding=UTF-8 -jar /home/Benchmark/build/Benchmark-impl/libs/benchmarks.jar com.linkedin.quickbenchmark.SomeBenchmark
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
	at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
	at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:263)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
	at org.openjdk.jmh.Main.main(Main.java:71)
```

Works fine with Gradle `4.*`

**Comment by hiteshsharma** [comment]
@johnrengelman any workaround or fix for this?

**Comment by Goooler** [comment]
This should be fixed in the latest version.
