### ISSUE TITLE
Relocated Groovy extensions are not working

### ISSUE THREAD

**Issue by lwolter** [GradleUp/shadow#467]
`import groovy.text.SimpleTemplateEngine

class SimpleTemplateEngineDateUtil {

    public static void main(args) {
        SimpleTemplateEngineTest()
    }

    static void SimpleTemplateEngineTest() {
        println new SimpleTemplateEngine(true).createTemplate('<%df = "dd.MM.yyyy" \ntf = "dd.MM.yyyy HH:mm:ss" %><% out << "Date:${new Date().format(tf)}"%>') .make([:]).toString()
    }

}`

run as shadow jar return this error:

`Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: java.util.Date.format() is applicable for argument types: (String) values: [dd.MM.yyyy HH:mm:ss]
Possible solutions: from(java.time.Instant), getAt(java.lang.String), parse(java.lang.String), print(java.lang.Object), print(java.io.PrintWriter)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at SimpleTemplateScript1.run(SimpleTemplateScript1.groovy:3)
	at groovy.text.SimpleTemplateEngine$SimpleTemplate$1.writeTo(SimpleTemplateEngine.java:176)
	at groovy.text.SimpleTemplateEngine$SimpleTemplate$1.toString(SimpleTemplateEngine.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:211)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at SimpleTemplateEngineDateUtil.SimpleTemplateEngineTest(SimpleTemplateEngineDateUtil.groovy:10)
	at SimpleTemplateEngineDateUtil.main(SimpleTemplateEngineDateUtil.groovy:6)`

Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: java.util.Date.format() is applicable for argument types: (String) values: [dd.MM.yyyy HH:mm:ss]
Possible solutions: from(java.time.Instant), getAt(java.lang.String), parse(java.lang.String), print(java.lang.Object), print(java.io.PrintWriter)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at SimpleTemplateScript1.run(SimpleTemplateScript1.groovy:3)
	at groovy.text.SimpleTemplateEngine$SimpleTemplate$1.writeTo(SimpleTemplateEngine.java:176)
	at groovy.text.SimpleTemplateEngine$SimpleTemplate$1.toString(SimpleTemplateEngine.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:211)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at SimpleTemplateEngineDateUtil.SimpleTemplateEngineTest(SimpleTemplateEngineDateUtil.groovy:10)
	at SimpleTemplateEngineDateUtil.main(SimpleTemplateEngineDateUtil.groovy:6)`

org.apache.groovy.dateutil.extensions (groovy-dateutil and groovytime)is part of the jar Archives

The execution without shadowJar is error-free.

**Comment by lwolter** [comment]
For Information: groovy 2.5.6, gradle 4.10.2, com.github.johnrengelman.shadow 4.0.4

**Comment by cebbec** [comment]
It seems to be related to groovy extension feature. No pb with groovy in 2.4.16 using groovy-all. Adding mergeGroovyExtensionModules doesn't help.

**Comment by lwolter** [comment]
I have added
`shadowJar {
    mergeGroovyExtensionModules()
}`
to my gradle build. Unfortunately the problem is not solved.

**Comment by Goooler** [comment]
Can you try out the latest versions?
