### ISSUE TITLE
I'm trying to create an uber jar but without success

### ISSUE THREAD

**Issue by Graou74** [GradleUp/shadow#523]
Hello,
If I understand the documentation, declaring the plugin 'com.github.johnrengelman.shadow' in the build.gradle file is enough,during build, to copy the dependencies in the generated jar file.
But even trying several other ways the jar file invariably remains empty of dependencies.

### Actual Behavior : A stacktrace due to lack of dependencies:
```
java -jar ./build/libs/TestJar.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
	at TestJar.Library.testDependecy(Library.java:16)
	at TestJar.Library.main(Library.java:22)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.Yaml
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```
### Gradle Build Script(s) :
```
plugins {
    id 'java-library'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
    id 'java'
}

repositories {
    jcenter()
}

dependencies {
    implementation group: 'org.yaml', name: 'snakeyaml', version: '1.25'
	
    testImplementation 'junit:junit:4.12'
}

jar {
    manifest {
        attributes 'Main-Class': 'TestJar.Library'
    }
}
```
### Java main class :
```
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestJar;

import java.util.Map;

import org.yaml.snakeyaml.Yaml;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void testDependecy() {
    	final Yaml yaml = new Yaml();
    	final Map<String, Object> map = yaml.load("prop: 2.0");
    	System.out.println("Test dependecy : " + map.get("prop"));
    }
    
    public static void main(String[] args) {
    	testDependecy();
    }
}
```
### Content of Shadow JAR :
```
jar tf ./build/libs/TestJar.jar
META-INF/
META-INF/MANIFEST.MF
TestJar/
TestJar/Library.class
```

I tried all the tracks that I could find on the web with always the same negative result.
Would anyone have an idea to solve this problem?

**Comment by DeepRobin** [comment]
Same here #528

**Comment by Proximyst** [comment]
@DeepRobin These are not related.

@Graou74 You need to stick to the *deprecated* `compile` configuration.

**Comment by Goooler** [comment]
It works with the latest versions.
