### ISSUE TITLE
java.lang.IllegalArgumentException: neither file nor directory

### ISSUE THREAD

**Issue by ZacSweers** [GradleUp/shadow#540]
### Shadow Version
5.2.0

### Gradle Version
6.1

### Expected Behavior
`shadowJar` task should pass. It's tricky, as it appears to only fail if building from a clean state, and succeeds if built after a previously successful compilation. Quoting from @rharter's local investigation

> Interestingly, `./gradlew clean check works fine`, and does run `shadowJar`. If I run `./gradlew clean build` after it, it fails.  If I run `./gradlew build` it works.  I’m guessing there’s just a missing dependency in the gradle task graph, so it’s missing something when it’s cleaned.

If we downgrade all the way to version 4.0.1, it works fine there.

### Actual Behavior

```
Caused by: java.lang.IllegalArgumentException: neither file nor directory

	at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:122)
	at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:95)
	at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:86)
	at shadow.org.vafer.jdependency.Clazzpath$addClazzpathUnit.call(Unknown Source)
	at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker$_closure2.doCall(UnusedTracker.groovy:24)
	at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker.<init>(UnusedTracker.groovy:24)
	at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker.forProject(UnusedTracker.groovy:51)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.createCopyAction(ShadowJar.java:101)
	at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:136)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.copy(ShadowJar.java:115)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
```

### Gradle Build Script(s)

Here is a public repro case: https://github.com/rharter/auto-value-gson/pull/243

**Comment by ZacSweers** [comment]
Just updating to mention this still happens with 6.2

**Comment by Goooler** [comment]
It should work with the latest versions.
