### ISSUE TITLE
 Problem trying to generate the jar

### ISSUE THREAD

**Issue by rodrigodevelms** [GradleUp/shadow#595]
Shadow version: 6.0.0
gradle version 6.6
ktor version 1.4
kotlin version 1.4

Hello everyone.
I am in a project with gradle multi modules and trying to generate a jar.
But the error always occurs:

* Exception is:

```
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.kotlin.jvm'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:215)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$resolvePluginRequests$4(DefaultPluginRequestApplicator.java:148)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:207)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:201)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:146)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:86)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:197)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:360)
	at Program.execute(Unknown Source)
```

This is my root gradle configuration:
build.gradle.kts:
```
plugins {
  kotlin("jvm")
  kotlin("plugin.serialization") apply false
  id("com.github.johnrengelman.shadow") apply false
  id("io.gitlab.arturbosch.detekt") apply false
  id("org.flywaydb.flyway") apply false
  `maven-publish`
}

group = "com.rjdesenvolvimento"
version = "0.0.1"

subprojects {
  group = "com.rjdesenvolvimento"
  version = "0.0.1"

  repositories {
    jcenter()
    maven(url = "https://kotlin.bintray.com/ktor") { name = "bintray-ktor" }
    maven(url = "http://packages.confluent.io/maven/")
    maven(url = "https://jitpack.io")
  }

  afterEvaluate {
    if (project.plugins.hasPlugin("org.jetbrains.kotlin.jvm")) {
      tasks {
        compileKotlin { kotlinOptions.jvmTarget = "11" }
        compileTestKotlin { kotlinOptions.jvmTarget = "11" }
        withType<io.gitlab.arturbosch.detekt.Detekt> { this.jvmTarget = "11" }
        test {
          useJUnitPlatform()
          testLogging {
            events("passed", "skipped", "failed")
          }
        }
      }
      publishing {
        publications {
          create<MavenPublication>("mavenKotlin") {
            from(components["kotlin"])
            pom {
              licenses {
                license {
                  name.set("The Apache License, Version 2.0")
                  url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                }
              }
            }
          }
        }
      }
    }
  }
}
```

settings.gradle.kts:
```
import de.fayard.dependencies.*

buildscript {
  repositories {
    gradlePluginPortal()
  }
  dependencies.classpath("de.fayard:dependencies:0.5.8")
}

plugins {
  id("com.gradle.enterprise").version("3.1.1")
}

bootstrapRefreshVersionsAndDependencies(
listOf(rootDir.resolve("dependencies-rules.txt").readText())
)

gradleEnterprise {
  buildScan {
    termsOfServiceUrl = "https://gradle.com/terms-of-service"
    termsOfServiceAgree = "yes"
  }
}

rootProject.name = "aries"

include("commons:commons.test")
findProject(":commons:commons.test")?.name = "commons.test"
include("commons:commons.patterns")
findProject(":commons:commons.patterns")?.name = "commons.patterns"
include("commons:commons.kafka")
findProject(":commons:commons.kafka")?.name = "commons.kafka"
include("commons:commons.orchestration")
findProject(":commons:commons.orchestration")?.name = "commons.orchestration"
include("commons:commons.consumer")
findProject(":commons:commons.consumer")?.name = "commons.consumer"
include("commons:commons.elasticsearch")
findProject(":commons:commons.elasticsearch")?.name = "commons.elasticsearch"
include("commons:commons.elasticsearch")
findProject(":commons:commons.elasticsearch")?.name = "commons.elasticsearch"
include("access:access.orchestration")
findProject(":access:access.orchestration")?.name = "access.orchestration"
include("access:access.consumer")
findProject(":access:access.consumer")?.name = "access.consumer"
include("company:company.orchestration")
findProject(":company:company.orchestration")?.name = "company.orchestration"
```

This is the configuration of the module I'm trying to generate the jar for. (access.orchestration)
```
plugins {
    application
    kotlin("jvm")
    kotlin("plugin.serialization")
    id("com.github.johnrengelman.shadow")
    id("io.gitlab.arturbosch.detekt")
    `maven-publish`
}

group = "com.rjdesenvolvimento"
version = "0.0.1"

application {
    mainClassName = "io.ktor.server.netty.EngineMain"
}

repositories {
    jcenter()
    maven { url = uri("https://kotlin.bintray.com/ktor") }
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    implementation(kotlin("stdlib", "_"))
    implementation("ch.qos.logback:logback-classic:_")
    implementation("io.ktor:ktor-server-netty:_")

    implementation("io.ktor:ktor-metrics:_")
    implementation("io.ktor:ktor-server-core:_")
    implementation("io.ktor:ktor-auth:_")
    implementation("io.ktor:ktor-auth-jwt:_")

    implementation(project(":commons:commons.orchestration"))
    implementation(project(":commons:commons.patterns"))
    implementation(project(":commons:commons.kafka"))
    implementation(project(":commons:commons.elasticsearch"))

    testImplementation("io.ktor:ktor-server-tests:_")
    testImplementation(project(":commons:commons.test"))
}

kotlin.sourceSets["main"].kotlin.srcDirs("src")
kotlin.sourceSets["test"].kotlin.srcDirs("test")

sourceSets["main"].resources.srcDirs("resources")
sourceSets["test"].resources.srcDirs("testresources")

detekt {
    buildUponDefaultConfig = false
    input = files("src")
    config = files("resources/detekt.yml")
    debug = true
    ignoreFailures = false
    reports {
        xml {
            enabled = true
            destination = file("build/reports/detekt.xml")
        }
        html {
            enabled = true
            destination = file("build/reports/detekt.html")
        }
        txt {
            enabled = true
            destination = file("build/reports/detekt.txt")
        }
        custom {
            reportId = "CustomJsonReport"
            destination = file("build/reports/detekt.json")
        }
    }
}

fun getProperty(propertyName: String): String =
    project.findProperty(propertyName).toString()

tasks {
    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().all {
        kotlinOptions.freeCompilerArgs += "-Xopt-in=kotlin.RequiresOptIn"
    }
}
```

I am quite lost. Could anyone help?

**Comment by Goooler** [comment]
This is not the issue of Shadow.
