### ISSUE TITLE
Plugin is incompatible with isolated projects feature

### ISSUE THREAD

**Issue by erdi** [GradleUp/shadow#907]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version

8.1.1

### Gradle Version

8.5

### Expected Behavior

Plugin does not violate [project isolation](https://gradle.github.io/configuration-cache/) constraints, no errors are raised when a project to which the plugin is applied which also enables project isolation is being imported into IntelliJ.

### Actual Behavior

An error is thrown when a project to which the plugin is applied which also enables project isolation is being imported into IntelliJ. The following stacktrace is present in the configuration cache report generated upon the error:
```
org.gradle.api.InvalidUserCodeException: Cannot access project ':' from project ':services'
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall$original(ShadowPlugin.groovy:24)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall(ShadowPlugin.groovy)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy:15)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:70)
	....
```

That's because [the plugin calls `getPlugins()` on the `rootProject` instance from sub projects](https://github.com/johnrengelman/shadow/blob/2f94a2558023b208ffb840471281703cb2c9b222/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy#L24) which is not compatible with isolated projects.

One fix for this problem would be to check if `com.gradle.enterprise` plugin is applied to the `Settings` object [(because that's what you should be applying the plugin in newer versions to according to the docs](https://docs.gradle.com/enterprise/gradle-plugin/#gradle_6_x_and_later)) rather than the root project object but sadly you cannot get to an instance of `Settings` from an instance of `Project`. Another fix would be for the `com.gradle.enterprise` plugin to register itself as a plugin on `Gradle` instance (to which you can get from an instance of `Project`) together with an instance of `GradleEnterpriseExtension` but for that we would probably need core Gradle team to change the implementation as I don't believe this is happening now (hard to tell given `com.gradle.enterprise` is closed source).

As a workaround, I will reverse engineer `com.github.jengelman.gradle.plugins.shadow.ShadowPlugin` as I have a convention plugin applying it in my project and simply boil it down to:
```
project.with {
    plugins.apply(ShadowBasePlugin)
    plugins.withType(JavaPlugin) {
        plugins.apply(ShadowJavaPlugin)
    }
}
```
Nevertheless, it would be good if this plugin was compatible with project isolation out of the box.

**Comment by Goooler** [comment]
Some limitations are tracked in https://github.com/gradle/gradle/issues/22514.

**Comment by 3flex** [comment]
Couple of things:
1. Does this code even work properly anymore? The plugin coordinates have changed to "com.gradle.develocity". Assuming it doesn't, could this feature just be dropped?
2. If there's a desire or need to keep it, could it be gated so it's only active if using Gradle 8.4 or below, or Gradle 8.5 if isolated projects is not being used? See "Build Features API" section in https://docs.gradle.org/8.5/release-notes.html#build-authoring-improvements

**Comment by liutikas** [comment]
There are two violations of project isolation in this plugin:

```
Exception at `com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall$original(ShadowPlugin.groovy:25)`
org.gradle.api.InvalidUserCodeException: Project ':compose' cannot access 'Project.plugins' functionality on another project ':'
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall$original(ShadowPlugin.groovy:25)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall(ShadowPlugin.groovy)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy:14)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
Exception at `com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall$original(ShadowPlugin.groovy:28)`
org.gradle.api.InvalidUserCodeException: Project ':compose' cannot access 'Project.plugins' functionality on another project ':'
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall$original(ShadowPlugin.groovy:28)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall(ShadowPlugin.groovy)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy:14)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by liutikas** [comment]
Created https://github.com/GradleUp/shadow/pull/993 to help users disable this develocity integration.

**Comment by liutikas** [comment]
Could we have a release to pick this up?

**Comment by Goooler** [comment]
https://github.com/GradleUp/shadow/releases/tag/8.3.3

**Comment by 3flex** [comment]
Can close this now then?

Thanks for turning this around so quickly both of you! I think I have one incompatible plugin to go before we can use this in detekt project.
