### ISSUE TITLE
minimize() incompatible with hikari

### ISSUE THREAD

**Issue by SergioK29** [GradleUp/shadow#972]
### Expected and Results

minimize() shouldn't break jars using hikari

### Reproduction steps

HikariConfig config = new HikariConfig();
config.setDriverClassName("com.mysql.cj.jdbc.Driver");

if minimize() step is done, error:

Exception in thread "main" java.lang.RuntimeException: Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:494)
        at me.test.webserver.MySQLStorageProvider.<init>(MySQLStorageProvider.java:35)
        at me.test.webserver.WebServer.main(WebServer.java:63)

### Anything else?

The breakage is probably because reflection, will shadow ever plan to support reflection for minimize step?

**Comment by Goooler** [comment]
Can you address a reproducer?

**Comment by Goooler** [comment]
A project to reproduce this issue.

**Comment by Goooler** [comment]
Look like you refed `com.mysql.cj.jdbc.Driver` via a string instead of a class, `minimize` step removed `Driver` as it's not refed. You can try out `com.mysql.cj.jdbc.Driver.class.getName()` or declare `exclude` for this dependency in `minimize` block.
